buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
    }
}

plugins {
  id 'maven-publish'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

publishing {
  repositories {
    maven {
      name = "reposiliteRepository"
      url = "https://reposilite.dashboards.steller.co/releases"
      credentials(PasswordCredentials)
      authentication {
        basic(BasicAuthentication)
      }
    }
  }
  publications {
    maven(MavenPublication) {
      groupId = "com.arthenica"
      artifactId = "ffmpeg-kit-https-gpl-no-gnutls"
      version = "6.0-5"
      // from components.java
    }
  }
}
